/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'alt-bg': 'var(--alt-bg)',
        'big-surface': 'var(--big-surface)',
        'inverse-iron-subtle': 'var(--inverse-iron-subtle)',
        'color-background': 'var(--color-background)',
        'color-foreground': 'var(--color-foreground)',
        'color-card': 'var(--color-card)',
        'color-card-foreground': 'var(--color-card-foreground)',
        'color-popover': 'var(--color-popover)',
        'color-popover-foreground': 'var(--color-popover-foreground)',
        'color-primary': 'var(--color-primary)',
        'color-primary-foreground': 'var(--color-primary-foreground)',
        'color-secondary': 'var(--color-secondary)',
        'color-secondary-foreground': 'var(--color-secondary-foreground)',
        'color-muted': 'var(--color-muted)',
        'color-muted-foreground': 'var(--color-muted-foreground)',
        'color-accent': 'var(--color-accent)',
        'color-accent-foreground': 'var(--color-accent-foreground)',
        'color-destructive': 'var(--color-destructive)',
        'color-border': 'var(--color-border)',
        'color-input': 'var(--color-input)',
        'color-ring': 'var(--color-ring)',
        'color-chart-1': 'var(--color-chart-1)',
        'color-chart-2': 'var(--color-chart-2)',
        'color-chart-3': 'var(--color-chart-3)',
        'color-chart-4': 'var(--color-chart-4)',
        'color-chart-5': 'var(--color-chart-5)',
        'color-sidebar': 'var(--color-sidebar)',
        'color-sidebar-foreground': 'var(--color-sidebar-foreground)',
        'color-sidebar-primary': 'var(--color-sidebar-primary)',
        'color-sidebar-primary-foreground': 'var(--color-sidebar-primary-foreground)',
        'color-sidebar-accent': 'var(--color-sidebar-accent)',
        'color-sidebar-accent-foreground': 'var(--color-sidebar-accent-foreground)',
        'color-sidebar-border': 'var(--color-sidebar-border)',
        'color-sidebar-ring': 'var(--color-sidebar-ring)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
      },
    },
  },
  plugins: [],
}; 